import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Card } from "../../components/ui/Card";
import { RiskBadge } from "../../components/ui/StatusBadge";
import { exportElementToPDF, generateMarketReportFilename } from "../../services/exportPDF";
import { Spinner } from "../../components/ui/LoadingSpinner";

function ReportPreview({ marketData, offerData }) {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  return (
    <div id="report-preview" className="bg-[#07091a] text-slate-100 p-8 space-y-6 min-h-[600px] rounded-2xl border border-white/10">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-white/10 pb-6">
        <div>
          <div className="text-2xl font-black text-white">Validation Report</div>
          <div className="text-sm text-slate-500 mt-1">Veryfii Validator — {date}</div>
        </div>
        <div className="text-right">
          <div className="text-xs text-slate-500">Generated by</div>
          <div className="text-sm font-bold text-blue-400">Veryfii Validator Pro</div>
        </div>
      </div>

      {/* Market section */}
      {marketData && (
        <div className="space-y-4">
          <div className="text-xs text-slate-500 uppercase tracking-wider font-semibold border-b border-white/8 pb-2">
            Market Intelligence — {marketData.niche}
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="text-xs text-slate-500">Total Score</div>
              <div className="text-3xl font-black text-blue-400">{marketData.totalScore}/10</div>
            </div>
            <div>
              <div className="text-xs text-slate-500">Recommendation</div>
              <RiskBadge level={marketData.recommendation} />
            </div>
          </div>

          {marketData.signals && (
            <div>
              <div className="text-xs text-slate-500 mb-2">Top Signals</div>
              {marketData.signals.slice(0, 3).map((s, i) => (
                <div key={i} className="text-sm text-slate-300 py-1 border-b border-white/5">
                  <span className="text-blue-400 font-mono">{s.source}:</span> {s.signal} — {s.data}
                </div>
              ))}
            </div>
          )}

          {marketData.competitors && (
            <div>
              <div className="text-xs text-slate-500 mb-2">Competitors</div>
              {marketData.competitors.slice(0, 3).map((c, i) => (
                <div key={i} className="text-sm text-slate-300 py-1 border-b border-white/5 flex justify-between">
                  <span>{c.name}</span>
                  <span className="text-slate-500 text-xs">{c.pricing}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Offer section */}
      {offerData?.offer && (
        <div className="space-y-4">
          <div className="text-xs text-slate-500 uppercase tracking-wider font-semibold border-b border-white/8 pb-2">
            Offer Framework (Hormozi)
          </div>

          {offerData.offer.pitch && (
            <div className="rounded-xl border border-blue-500/20 bg-blue-500/8 p-4">
              <div className="text-xs text-slate-500 mb-2">Final Pitch</div>
              <p className="text-sm text-slate-200 leading-relaxed">
                {typeof offerData.offer.pitch === "string" ? offerData.offer.pitch : ""}
              </p>
            </div>
          )}

          {offerData.offer.pricing && (
            <div className="grid grid-cols-2 gap-4">
              <div>
                <div className="text-xs text-slate-500">Price</div>
                <div className="text-xl font-black text-emerald-400">{offerData.offer.pricing.price}</div>
              </div>
              <div>
                <div className="text-xs text-slate-500">Model</div>
                <div className="text-sm text-slate-200">{offerData.offer.pricing.model}</div>
              </div>
            </div>
          )}

          {offerData.offer.guarantee && (
            <div>
              <div className="text-xs text-slate-500 mb-1">Guarantee</div>
              <div className="text-sm text-slate-200">{offerData.offer.guarantee.headline}</div>
            </div>
          )}
        </div>
      )}

      {/* Disclaimer */}
      <div className="border-t border-white/8 pt-4">
        <p className="text-xs text-slate-600">
          This report is generated by Veryfii Validator for informational purposes only.
          All trade instrument results require official bank confirmation.
          Market intelligence is AI-generated and should be independently verified.
        </p>
      </div>
    </div>
  );
}

export default function ReportExport() {
  const navigate = useNavigate();
  const [marketData, setMarketData] = useState(null);
  const [offerData, setOfferData] = useState(null);
  const [exporting, setExporting] = useState(false);
  const [done, setDone] = useState(false);

  useEffect(() => {
    const market = sessionStorage.getItem("tv_market_result");
    const offer = sessionStorage.getItem("tv_offer_result");
    if (market) {
      try { setMarketData(JSON.parse(market)); } catch { /* ignore */ }
    }
    if (offer) {
      try { setOfferData(JSON.parse(offer)); } catch { /* ignore */ }
    }
  }, []);

  async function downloadPDF() {
    setExporting(true);
    setDone(false);
    try {
      const filename = marketData
        ? generateMarketReportFilename(marketData.niche || "report")
        : "veryfii-report.pdf";
      await exportElementToPDF("report-preview", filename);
      setDone(true);
    } catch (e) {
      console.error("PDF export failed:", e);
    } finally {
      setExporting(false);
    }
  }

  const hasData = marketData || offerData;

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-black text-slate-100">Generate Validation Report</h1>
          <p className="text-sm text-slate-500 mt-1">Export your analysis as a professional PDF</p>
        </div>

        <button
          onClick={downloadPDF}
          disabled={exporting || !hasData}
          data-testid="download-pdf-btn"
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 text-white font-bold px-5 py-2.5 rounded-xl text-sm transition"
        >
          {exporting ? <Spinner size={16} /> : (
            <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          )}
          {exporting ? "Generating…" : "Download PDF Report"}
        </button>
      </div>

      {done && (
        <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-300">
          ✓ Report downloaded successfully.
        </div>
      )}

      {!hasData && (
        <div className="rounded-2xl border border-amber-500/30 bg-amber-500/8 p-5 flex items-center justify-between gap-4">
          <div>
            <div className="text-sm font-bold text-amber-300">No data to export</div>
            <div className="text-xs text-slate-500 mt-0.5">Run a Market Intelligence or Trade Validation first.</div>
          </div>
          <button
            onClick={() => navigate("/market")}
            className="bg-blue-600 hover:bg-blue-500 text-white font-bold px-4 py-2 rounded-xl text-sm transition whitespace-nowrap"
          >
            Go to Market →
          </button>
        </div>
      )}

      {/* Preview */}
      <ReportPreview marketData={marketData} offerData={offerData} />
    </div>
  );
}
